from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

import sqlite3
import pandas as pd


def generate_intelligence_report():

    filename = (
        "reports/weekly_intelligence_report.pdf"
    )

    doc = SimpleDocTemplate(
        filename
    )

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            "Cyber Intelligence Weekly Report",
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # =====================================
    # COMPLAINTS
    # =====================================

    conn = sqlite3.connect(
        "database/complaints.db"
    )

    complaints = pd.read_sql(
        "SELECT * FROM complaints",
        conn
    )

    conn.close()

    total_complaints = len(
        complaints
    )

    critical_cases = len(
        complaints[
            complaints["priority"] == "Critical"
        ]
    )

    resolved_cases = len(
        complaints[
            complaints["status"] == "Resolved"
        ]
    )

    content.append(
        Paragraph(
            f"Total Complaints: {total_complaints}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"Critical Cases: {critical_cases}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"Resolved Cases: {resolved_cases}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    # =====================================
    # THREAT INTELLIGENCE
    # =====================================

    conn = sqlite3.connect(
        "database/cybercrime.db"
    )

    intel = pd.read_sql(
        "SELECT * FROM intelligence_data",
        conn
    )

    conn.close()

    total_articles = len(
        intel
    )

    high_risk = len(
        intel[
            intel["threat_score"] >= 30
        ]
    )

    content.append(
        Paragraph(
            f"Intelligence Articles: {total_articles}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"High Risk Threats: {high_risk}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Generated by Cyber Crime Intelligence Platform",
            styles["Italic"]
        )
    )

    doc.build(
        content
    )

    return filename